version: '3.8'
services:
  # Application service
  web:
    build:
      context: .
      args:
        requirements_file: requirements/local.txt
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
    restart: always
    networks:
      - app-network


networks:
  app-network:
    driver: bridge